
POST https://qo0z1jwsgi.execute-api.us-east-1.amazonaws.com/prod/spaces
content-type: application/json

 {
    "location": "Kyiv"
 }
###

GET https://qo0z1jwsgi.execute-api.us-east-1.amazonaws.com/prod/spaces?id=23432
###

DELETE https://qo0z1jwsgi.execute-api.us-east-1.amazonaws.com/prod/spaces?id=23432
###

PUT https://qo0z1jwsgi.execute-api.us-east-1.amazonaws.com/prod/spaces?id=23432
content-type: application/json

 {
    "location": "Kyiv"
 }
###